/*
===========================================================
 CINEVERSE ANALYTICS
 DAY 02 - SQL JOINS
 TOPIC: INNER JOIN, LEFT JOIN
 AUTHOR: NAILA SELIMZADE
 DATABASE: POSTGRESQL
===========================================================
*/

-- =========================================================
--1.DISPLAY EACH MOVIE TOGETHER WITH ITS PRODUCTION STUDIO
-- AND STUDIO HEADQUARTERS.
-- =========================================================

SELECT MOVIE_ID,TITLE,GENRE,RELEASE_YEAR,STUDIO_NAME,HEADQUARTERS
FROM MOVIES M
INNER JOIN STUDIOS S
ON M.STUDIO_ID=S.STUDIO_ID
ORDER BY RELEASE_YEAR DESC;


-- =========================================================
--2.DISPLAY EVERY ACTOR TOGETHER WITH THE MOVIES THEY STARRED IN.
-- =========================================================

SELECT ACTOR_ID,FIRST_NAME||' '||LAST_NAME AS ACTOR_NAME,TITLE,GENRE,ROLE_NAME
FROM ACTORS A
INNER JOIN MOVIE_CAST MC
ON A.ACTOR_ID=MC.ACTOR_ID
INNER JOIN MOVIES M
ON MC.MOVIE_ID=M.MOVIE_ID
ORDER BY ACTOR_NAME;


-- =========================================================
--3.DISPLAY EACH ACTOR'S FULL NAME, MOVIE TITLE,
-- STUDIO NAME AND ROLE.
-- =========================================================

SELECT FIRST_NAME||' '||LAST_NAME AS ACTOR_NAME,TITLE,STUDIO_NAME,ROLE_NAME
FROM ACTORS A
INNER JOIN MOVIE_CAST MC
ON A.ACTOR_ID=MC.ACTOR_ID
INNER JOIN MOVIES M
ON MC.MOVIE_ID=M.MOVIE_ID
INNER JOIN STUDIOS S
ON M.STUDIO_ID=S.STUDIO_ID
ORDER BY STUDIO_NAME,ACTOR_NAME;


-- =========================================================
--4.DISPLAY ALL ACTORS TOGETHER WITH THEIR AWARDS.
-- INCLUDE ACTORS WHO HAVE NOT RECEIVED ANY AWARDS.
-- =========================================================

SELECT ACTOR_ID,FIRST_NAME||' '||LAST_NAME AS ACTOR_NAME,
COALESCE(AWARD_NAME,'NO AWARD') AS AWARD_NAME,
AWARD_YEAR
FROM ACTORS A
LEFT JOIN AWARDS AW
ON A.ACTOR_ID=AW.ACTOR_ID
ORDER BY ACTOR_NAME;


-- =========================================================
--5.DISPLAY EACH MOVIE TOGETHER WITH ITS PRODUCTION STUDIO
-- AND TOTAL BOX OFFICE REVENUE.
-- =========================================================

SELECT TITLE,STUDIO_NAME,SUM(REVENUE) AS TOTAL_REVENUE,
SUM(TICKETS_SOLD) AS TOTAL_TICKETS
FROM MOVIES M
INNER JOIN STUDIOS S
ON M.STUDIO_ID=S.STUDIO_ID
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID
GROUP BY TITLE,STUDIO_NAME
ORDER BY TOTAL_REVENUE DESC;


-- =========================================================
--6.DISPLAY THE NUMBER OF ACTORS IN EACH MOVIE.
-- =========================================================

SELECT TITLE,COUNT(ACTOR_ID) AS TOTAL_ACTORS
FROM MOVIES M
INNER JOIN MOVIE_CAST MC
ON M.MOVIE_ID=MC.MOVIE_ID
GROUP BY TITLE
ORDER BY TOTAL_ACTORS DESC;
