/*
===========================================================
 CINEVERSE ANALYTICS
 DAY 03 - GROUP BY & HAVING
 TOPIC: AGGREGATION FUNCTIONS
 AUTHOR: NAILA SELIMZADE
 DATABASE: POSTGRESQL
*/
-- =========================================================
--1.DISPLAY THE TOTAL BOX OFFICE REVENUE,
-- TOTAL TICKETS SOLD AND NUMBER OF SALES RECORDS
-- FOR EACH MOVIE.
-- =========================================================

SELECT M.TITLE,
SUM(B.REVENUE) AS TOTAL_REVENUE,
SUM(B.TICKETS_SOLD) AS TOTAL_TICKETS,
COUNT(B.REVENUE_ID) AS TOTAL_MONTHS
FROM MOVIES M
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID
GROUP BY M.TITLE
ORDER BY TOTAL_REVENUE DESC;


-- =========================================================
--2.DISPLAY THE AVERAGE, MINIMUM AND MAXIMUM MOVIE
-- BUDGET FOR EACH GENRE.
-- =========================================================

SELECT GENRE,
COUNT(*) AS TOTAL_MOVIES,
ROUND(AVG(BUDGET),2) AS AVERAGE_BUDGET,
MIN(BUDGET) AS MINIMUM_BUDGET,
MAX(BUDGET) AS MAXIMUM_BUDGET
FROM MOVIES
GROUP BY GENRE
ORDER BY AVERAGE_BUDGET DESC;


-- =========================================================
--3.DISPLAY THE NUMBER OF MOVIES
-- PRODUCED BY EACH STUDIO.
-- =========================================================

SELECT S.STUDIO_NAME,
COUNT(M.MOVIE_ID) AS TOTAL_MOVIES
FROM STUDIOS S
INNER JOIN MOVIES M
ON S.STUDIO_ID=M.STUDIO_ID
GROUP BY S.STUDIO_NAME
ORDER BY TOTAL_MOVIES DESC;


-- =========================================================
--4.DISPLAY GENRES THAT CONTAIN
-- AT LEAST THREE MOVIES.
-- =========================================================

SELECT GENRE,
COUNT(MOVIE_ID) AS TOTAL_MOVIES
FROM MOVIES
GROUP BY GENRE
HAVING COUNT(MOVIE_ID)>=3
ORDER BY TOTAL_MOVIES DESC;


-- =========================================================
--5.DISPLAY STUDIOS WITH A TOTAL BOX OFFICE
-- REVENUE GREATER THAN 300 MILLION.
-- =========================================================

SELECT S.STUDIO_NAME,
SUM(B.REVENUE) AS TOTAL_REVENUE
FROM STUDIOS S
INNER JOIN MOVIES M
ON S.STUDIO_ID=M.STUDIO_ID
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID
GROUP BY S.STUDIO_NAME
HAVING SUM(B.REVENUE)>300000000
ORDER BY TOTAL_REVENUE DESC;


-- =========================================================
--6.DISPLAY THE TOTAL NUMBER OF MOVIES
-- EACH ACTOR HAS APPEARED IN.
-- =========================================================

SELECT
A.FIRST_NAME||' '||A.LAST_NAME AS ACTOR_NAME,
COUNT(MC.MOVIE_ID) AS TOTAL_MOVIES
FROM ACTORS A
INNER JOIN MOVIE_CAST MC
ON A.ACTOR_ID=MC.ACTOR_ID
GROUP BY
A.FIRST_NAME,
A.LAST_NAME
ORDER BY TOTAL_MOVIES DESC;


-- =========================================================
--7.DISPLAY THE TOP 5 HIGHEST-GROSSING MOVIES
-- BASED ON TOTAL BOX OFFICE REVENUE.
-- =========================================================

SELECT
M.TITLE,
SUM(B.REVENUE) AS TOTAL_REVENUE
FROM MOVIES M
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID
GROUP BY M.TITLE
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;


-- =========================================================
--8.DISPLAY STUDIOS THAT HAVE PRODUCED
-- MORE THAN THREE MOVIES.
-- =========================================================

SELECT
S.STUDIO_NAME,
COUNT(M.MOVIE_ID) AS TOTAL_MOVIES
FROM STUDIOS S
INNER JOIN MOVIES M
ON S.STUDIO_ID=M.STUDIO_ID
GROUP BY S.STUDIO_NAME
HAVING COUNT(M.MOVIE_ID)>3
ORDER BY TOTAL_MOVIES DESC;
