/*
=========================================
 CINEVERSE ANALYTICS
 DAY 04 - SUBQUERY & CTE
=========================================
*/

-- TASK 1 | MOVIES WITH ABOVE-AVERAGE BUDGET

SELECT TITLE, GENRE, BUDGET
FROM MOVIES
WHERE BUDGET>(SELECT AVG(BUDGET) FROM MOVIES)
ORDER BY BUDGET DESC;

-- TASK 2 | ACTORS WHO APPEARED IN MORE THAN ONE MOVIE

SELECT FIRST_NAME||' '||LAST_NAME AS ACTOR_NAME
FROM ACTORS WHERE ACTOR_ID IN
( SELECT ACTOR_ID
FROM MOVIE_CAST
GROUP BY ACTOR_ID
HAVING COUNT(MOVIE_ID)>1 )
ORDER BY ACTOR_NAME;

-- TASK 3 | STUDIO WITH THE HIGHEST TOTAL REVENUE (CTE)

WITH STUDIO_REVENUE AS
(SELECT S.STUDIO_NAME,
SUM(B.REVENUE) AS TOTAL_REVENUE FROM STUDIOS S
INNER JOIN MOVIES M
ON S.STUDIO_ID=M.STUDIO_ID
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID
GROUP BY S.STUDIO_NAME)
SELECT * FROM STUDIO_REVENUE
WHERE TOTAL_REVENUE=
(SELECT MAX(TOTAL_REVENUE)
FROM STUDIO_REVENUE);

-- TASK 4 | MOVIES RELEASED AFTER THE AVERAGE RELEASE YEAR

SELECT TITLE,
RELEASE_YEAR
FROM MOVIES
WHERE RELEASE_YEAR>
( SELECT AVG(RELEASE_YEAR)
FROM MOVIES )
ORDER BY RELEASE_YEAR DESC;

-- TASK 5 | TOP REVENUE MOVIES USING CTE

WITH MOVIE_REVENUE AS
( SELECT M.TITLE,
SUM(B.REVENUE) AS TOTAL_REVENUE
FROM MOVIES M
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID
GROUP BY M.TITLE) 
SELECT * FROM MOVIE_REVENUE
ORDER BY TOTAL_REVENUE DESC LIMIT 5;

