/*
=========================================
 CINEVERSE ANALYTICS
 DAY 05 - WINDOW FUNCTIONS
=========================================
*/

-- TASK 1 | RANK MOVIES BY TOTAL BOX OFFICE REVENUE

SELECT M.TITLE,
SUM(B.REVENUE) AS TOTAL_REVENUE,
RANK() OVER(ORDER BY SUM(B.REVENUE) DESC) AS REVENUE_RANK
FROM MOVIES M
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID
GROUP BY M.TITLE
ORDER BY REVENUE_RANK;


-- TASK 2 | ASSIGN ROW NUMBERS TO MOVIES WITHIN EACH STUDIO

SELECT S.STUDIO_NAME, M.TITLE, M.RELEASE_YEAR,
ROW_NUMBER() OVER
(PARTITION BY S.STUDIO_NAME
ORDER BY M.RELEASE_YEAR DESC) AS MOVIE_NUMBER
FROM MOVIES M
INNER JOIN STUDIOS S
ON M.STUDIO_ID=S.STUDIO_ID;


-- TASK 3 | RANK MOVIES INSIDE EACH GENRE BY BUDGET

SELECT TITLE, GENRE, BUDGET,
DENSE_RANK() OVER
(PARTITION BY GENRE
ORDER BY BUDGET DESC) AS GENRE_RANK
FROM MOVIES
ORDER BY GENRE,GENRE_RANK;


-- TASK 4 | DISPLAY RUNNING TOTAL OF REVENUE FOR EACH MOVIE

SELECT M.TITLE, B.REVENUE_MONTH, B.REVENUE,
SUM(B.REVENUE) OVER
(PARTITION BY M.TITLE
ORDER BY B.REVENUE_MONTH
ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING_TOTAL
FROM MOVIES M
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID
ORDER BY M.TITLE,B.REVENUE_MONTH;


-- TASK 5 | COMPARE CURRENT MONTH REVENUE WITH PREVIOUS MONTH

SELECT M.TITLE, B.REVENUE_MONTH, B.REVENUE,
LAG(B.REVENUE) OVER
(PARTITION BY M.TITLE
ORDER BY B.REVENUE_MONTH ) AS PREVIOUS_REVENUE
FROM MOVIES M
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID;


-- TASK 6 | DISPLAY THE NEXT MONTH'S REVENUE

SELECT M.TITLE, B.REVENUE_MONTH, B.REVENUE,
LEAD(B.REVENUE) OVER(
PARTITION BY M.TITLE
ORDER BY B.REVENUE_MONTH
) AS NEXT_REVENUE
FROM MOVIES M
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID;


-- TASK 7 | FIND THE TOP REVENUE MOVIE FROM EACH STUDIO

WITH MOVIE_REVENUE AS
(SELECT S.STUDIO_NAME, M.TITLE,
SUM(B.REVENUE) AS TOTAL_REVENUE,
ROW_NUMBER() OVER
(PARTITION BY S.STUDIO_NAME
ORDER BY SUM(B.REVENUE) DESC) AS RN
FROM STUDIOS S
INNER JOIN MOVIES M
ON S.STUDIO_ID=M.STUDIO_ID
INNER JOIN BOX_OFFICE B
ON M.MOVIE_ID=B.MOVIE_ID
GROUP BY S.STUDIO_NAME,M.TITLE)
SELECT STUDIO_NAME, TITLE, TOTAL_REVENUE
FROM MOVIE_REVENUE
WHERE RN=1;
